---
# Defines deployment design and assigns role to server groups

- hosts: mons
  become: True
  roles:
  - ceph-mon
  post_tasks:
  - name: Get CRUSH tunables
    shell: ceph osd crush show-tunables
    run_once: True
    register: raw_prev_crush_tunables
  - set_fact:
      prev_crush_tunables: "{{ raw_prev_crush_tunables.stdout|from_json }}"
  - name: Fetch current CRUSH map
    shell: ceph osd getcrushmap -o crush.map
    run_once: True
  - name: Adjust CRUSH tunables in a local copy of CRUSH map
    shell: crushtool -i crush.map  --set-{{ item.key }} {{ item.value }} -o crush.map
    when: prev_crush_tunables[item.key] != item.value
    with_dict: crush_tunables
    run_once: True
  - name: Set the new CRUSH map
    shell: ceph osd setcrushmap -i crush.map
    run_once: True

- hosts: osds
  become: True
  roles:
  - ceph-osd

- hosts: rgws
  become: True
  roles:
  - ceph-rgw

- hosts: clients
  become: True
  roles:
  - ceph-client
  post_tasks:
  - name: Install fio utility
    apt: name=fio state=present
    when:
      - ansible_os_family == 'Debian'
  - name: Copy benchmark/test script
    copy: src=rbd-test.sh dest=/usr/local/sbin/rbd-test.sh owner=root group=root mode=0755
