---
# Defines deployment design and assigns role to server groups

- hosts: all
  become: True
  pre_tasks:
  - include: ./tasks/aptrepos.yml
  - include: ./tasks/timesync.yml
    when:
    - sync_time
    - ntp_server is defined

- hosts: mons
  become: True
  roles:
  - ceph-mon
  post_tasks:
  - include: ./tasks/crushtunables.yml

- hosts: osds
  become: True
  roles:
  - ceph-osd
  pre_tasks:
  - include: ./tasks/zapdisks.yml
    when: zap_block_devs

- hosts: rgws
  become: True
  roles:
  - ceph-rgw

- hosts: clients
  become: True
  roles:
  - ceph-client
  post_tasks:
  - include: ./tasks/benchmark.yml
